[workspace]
members = [
    "boot-core",
    "boot-cw-plus",
    "packages/*",
    # "template"
]

[workspace.package]
version = "0.5.1"
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/Abstract-OS/BOOT"

[workspace.dependencies]
cosmwasm-std = { version = "1.1" }
cw-multi-test = { version = "0.16.0"}
anyhow = "1.0"
boot-contract-derive = {path = "packages/boot-contract-derive", version = "0.5.1"}
boot-fns-derive = {path = "packages/boot-fns-derive", version = "0.5.1"}
boot-core ={path ="boot-core", version = "0.5.1"}
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[patch.crates-io]
cosmrs = {git = "https://github.com/Abstract-OS/cosmos-rust.git", features=["dev","cosmwasm","grpc"]}