[package]
name = "boot-core"
version = "0.1.0"
authors = ["CyberHoward <cyberhoward@protonmail.com>"]
edition = "2021"
description = "Scripting library for deploying and interacting with CosmWasm smart-contracts"
license = "Apache-2.0"
repository = "https://github.com/CyberHoward/cosm-rust-script"
keywords = ["cosmwasm", "blockchain"]
categories = ["development-tools", "api-bindings"]
readme = "README.md"

exclude = [
    ".env",
]

[[example]]
name = "cw20"

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
tokio = { version = "1.4", features = ["full"] }
tonic = "0.8.1"
secp256k1 = { version = "0.20.3", default-features = false }
log="0.4.14"
anyhow="1.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.9"}
base64 = "0.13.0"
dotenv="0.15.0"
prost = "0.10"
hkd32= { version="0.5.0", features=["bip39","mnemonic","bech32"] }
bitcoin="0.27.1"
rust-crypto = "^0.2"
rand_core = { version = "0.5", default-features = false }
ed25519-dalek = { version = "1", features = ["serde"] }
hex="0.4.3"
env_logger = "0.8.3"
erased-serde = "0.3"
eyre = "0.6"
lazy_static="1.4"
rust_decimal="1.12.2"
rust_decimal_macros="1.12.2"
regex="1"
cosmrs = {version = "0.9.0", features=["dev","cosmwasm","grpc"]}
# cosmos-sdk-proto = {version = "0.14.0", features=["cosmwasm","grpc-transport"]}
chrono= "0.4"
cosmwasm-std = "1.0.0"
cw-multi-test = "0.15.0"
schemars = "0.8.10"
base16 = "0.2.1"

[dev-dependencies]
boot-plus = {path = "../boot-plus"}
